# Runner
FROM containers.chewed-k8s.net/docker_hub_cache/library/nginx:1.23-alpine AS runner
COPY ./lib /usr/share/nginx/html/lib
COPY ./*.html /usr/share/nginx/html/
COPY ./k8s/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk update
RUN apk upgrade

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
